#!/bin/bash

pushd $DOTFILES

## NOTE iterate through sed output
## https://stackoverflow.com/a/49044136
while IFS="" read -r p || [ -n "$p" ]
do
    echo "Removing $p"
    stow -D $p
done < $DOTFILES/.stow-folders

popd
