#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo "copying $SCRIPT_DIR into ~/.dotfiles..."

mkdir ~/.dotfiles
cp "$SCRIPT_DIR" ~/.dotfiles
echo "done copying $SCRIPT_DIR into ~/.dotfiles"

pushd ~/.dotfiles

./ubuntu reinstall

pushd ~
