#!/bin/bash

# not using dpkg (which is recommended for scripting) instead of apt 
# since dpkg doesn't seem to also get dependencies 

cat "$DOTFILES/.apt-install-list" | tr '\n' ' ' | xargs apt install -y	
