#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tmux,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

# Install all brew apps
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
cat homebrew/apps.txt | xargs brew install
cat homebrew/casks.txt | xargs brew install --cask

# Install Chrome Extensions
sudo ~/.dotfiles/bin/.local/scripts/chrome_extensions_install

echo "Please manually sign in to the App Store, then run the script mas-install <email> <password>"
