#!/usr/bin/env zsh

pushd ~

rm -rf ~/.dotfiles
cp -r ~/projects/.dotfiles ~/.dotfiles

# Install all brew apps
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
cat install-lists/unix-utilities.txt | xargs brew install
cat install-lists/macos-utilities.txt | xargs brew install
cat install-lists/homebrew-casks.txt | xargs brew install --cask

# Install Chrome Extensions
sudo ~/.dotfiles/bin/.local/scripts/chrome_extensions_install

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tmux,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

tmux

echo "Please manually sign in to the App Store, then run the script mas-install <email> <password>"

popd
