#!/usr/bin/env zsh

pushd ~ 

sudo rm -rf ~/.dotfiles
sudo cp -r /home/deck/projects/.dotfiles ~/.dotfiles

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

cat ~/.dotfiles/install-lists/unix-utilities.txt | sudo xargs apt-get install -y

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tmux,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

tmux

popd
