#!/usr/bin/env zsh

pushd ~

sudo rm -rf ~/.dotfiles
sudo cp -r /home/deck/projects/.dotfiles ~/.dotfiles

# Install c-lang
sudo apt install lsb-release wget software-properties-common gnupg

wget https://apt.llvm.org/llvm.sh
sudo chmod u+x llvm.sh
sudo ./llvm.sh 17
mv /bin/clang-17 /bin/clang
clang --version

# Install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

cat ~/.dotfiles/install-lists/unix-utilities.txt | sudo xargs apt-get install -y

# TODO: curl neovim v0.9.4, untar it, and add it to the path
# TODO: https://github.com/neovim/neovim/releases
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tmux,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

tmux

popd
