#!/usr/bin/bash

reinstall="$1"

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

if [[ ! -z reinstall ]]; then
	sudo DOTFILES=$DOTFILES $DOTFILES/install
fi

DOTFILES=$DOTFILES $DOTFILES/stow-folders

source $HOME/.bash_profile
source $HOME/.bashrc

